//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public int ID { get; set; }
        public int idGame { get; set; }
        public Nullable<int> idPlatform { get; set; }
        public Nullable<int> MainGenre { get; set; }
        public Nullable<int> IdPublisher { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Release { get; set; }
        public Nullable<int> IdAgeLimit { get; set; }
    
        public virtual AgeLimit AgeLimit { get; set; }
        public virtual Games Games { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
