//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id_Sale { get; set; }
        public int id_Game { get; set; }
        public System.DateTime DateofSale { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
